import type { ColorTheme } from "./index";

export const lightTheme: ColorTheme = {
  directory: { bg: "#ff6b47", fg: "#ffffff" },
  git: { bg: "#4fb3d9", fg: "#ffffff" },
  model: { bg: "#87ceeb", fg: "#000000" },
  session: { bg: "#da70d6", fg: "#ffffff" },
  block: { bg: "#6366f1", fg: "#ffffff" },
  today: { bg: "#10b981", fg: "#ffffff" },
  tmux: { bg: "#32cd32", fg: "#ffffff" },
  context: { bg: "#718096", fg: "#ffffff" },
  metrics: { bg: "#6b7280", fg: "#ffffff" },
  version: { bg: "#8b7dd8", fg: "#ffffff" },
  omcModeActive: { bg: "#ec4899", fg: "#ffffff" },
  omcModeInactive: { bg: "#9ca3af", fg: "#4b5563" },
  omcRalphActive: { bg: "#3b82f6", fg: "#ffffff" },
  omcRalphWarn: { bg: "#f59e0b", fg: "#000000" },
  omcRalphMax: { bg: "#ef4444", fg: "#ffffff" },
  omcRalphInactive: { bg: "#9ca3af", fg: "#4b5563" },
  omcAgentsActive: { bg: "#8b5cf6", fg: "#ffffff" },
  omcAgentsInactive: { bg: "#9ca3af", fg: "#4b5563" },
  omcSkillActive: { bg: "#0891b2", fg: "#ffffff" },   // cyan-600
  omcSkillInactive: { bg: "#e5e7eb", fg: "#6b7280" },
  omcAgentOpus: { bg: "#ffffff", fg: "#ff1493" },
  omcAgentSonnet: { bg: "#ffffff", fg: "#795e26" },
  omcAgentHaiku: { bg: "#ffffff", fg: "#008000" },
};

export const lightAnsi256Theme: ColorTheme = {
  directory: { bg: "#ff5f5f", fg: "#ffffff" },
  git: { bg: "#5fafff", fg: "#ffffff" },
  model: { bg: "#87d7ff", fg: "#000000" },
  session: { bg: "#ff5fff", fg: "#ffffff" },
  block: { bg: "#5f5fff", fg: "#ffffff" },
  today: { bg: "#00d787", fg: "#ffffff" },
  tmux: { bg: "#00ff5f", fg: "#ffffff" },
  context: { bg: "#808080", fg: "#ffffff" },
  metrics: { bg: "#767676", fg: "#ffffff" },
  version: { bg: "#af87ff", fg: "#ffffff" },
  omcModeActive: { bg: "#ff5fd7", fg: "#ffffff" },
  omcModeInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcRalphActive: { bg: "#5f87ff", fg: "#ffffff" },
  omcRalphWarn: { bg: "#ffaf00", fg: "#000000" },
  omcRalphMax: { bg: "#ff5f5f", fg: "#ffffff" },
  omcRalphInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcAgentsActive: { bg: "#875fff", fg: "#ffffff" },
  omcAgentsInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcSkillActive: { bg: "#00afaf", fg: "#ffffff" },
  omcSkillInactive: { bg: "#d0d0d0", fg: "#767676" },
  omcAgentOpus: { bg: "#ffffff", fg: "#ff5f87" },
  omcAgentSonnet: { bg: "#ffffff", fg: "#af8700" },
  omcAgentHaiku: { bg: "#ffffff", fg: "#008700" },
};

export const lightAnsiTheme: ColorTheme = {
  directory: { bg: "#ff5f5f", fg: "#ffffff" },
  git: { bg: "#5fafff", fg: "#ffffff" },
  model: { bg: "#87d7ff", fg: "#000000" },
  session: { bg: "#ff5fff", fg: "#ffffff" },
  block: { bg: "#5f5fff", fg: "#ffffff" },
  today: { bg: "#00d787", fg: "#ffffff" },
  tmux: { bg: "#00ff5f", fg: "#ffffff" },
  context: { bg: "#808080", fg: "#ffffff" },
  metrics: { bg: "#767676", fg: "#ffffff" },
  version: { bg: "#af87ff", fg: "#ffffff" },
  omcModeActive: { bg: "#ff5fd7", fg: "#ffffff" },
  omcModeInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcRalphActive: { bg: "#5f87ff", fg: "#ffffff" },
  omcRalphWarn: { bg: "#ffaf00", fg: "#000000" },
  omcRalphMax: { bg: "#ff5f5f", fg: "#ffffff" },
  omcRalphInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcAgentsActive: { bg: "#875fff", fg: "#ffffff" },
  omcAgentsInactive: { bg: "#a8a8a8", fg: "#585858" },
  omcSkillActive: { bg: "#00afaf", fg: "#ffffff" },
  omcSkillInactive: { bg: "#d0d0d0", fg: "#767676" },
  omcAgentOpus: { bg: "#ffffff", fg: "#ff0000" },
  omcAgentSonnet: { bg: "#ffffff", fg: "#ffaf00" },
  omcAgentHaiku: { bg: "#ffffff", fg: "#00ff00" },
};
