export const RESET_CODE = "\x1b[0m";

export const SYMBOLS = {
  right: "\uE0B0",
  left_rounded: "\uE0B6",
  right_rounded: "\uE0B4",
  branch: "⎇",
  model: "✱",
  git_clean: "✓",
  git_dirty: "●",
  git_conflicts: "⚠",
  git_ahead: "↑",
  git_behind: "↓",
  git_worktree: "⧉",
  git_tag: "⌂",
  git_sha: "♯",
  git_upstream: "→",
  git_stash: "⧇",
  git_time: "◷",
  session_cost: "§",
  block_cost: "◱",
  today_cost: "☉",
  context_time: "◔",
  metrics_response: "⧖",
  metrics_last_response: "Δ",
  metrics_duration: "⧗",
  metrics_messages: "⟐",
  metrics_lines_added: "+",
  metrics_lines_removed: "-",
  metrics_burn: "⟢",
  version: "◈",
  omc_mode_ultrawork: "⚡",
  omc_mode_autopilot: "🤖",
  omc_mode_ecomode: "🌿",
  omc_mode_inactive: "◌",
  omc_ralph: "⟳",
  omc_agents: "◎",
  omc_skill: "⚙",
} as const;

export const TEXT_SYMBOLS = {
  right: "\uE0B0",
  left_rounded: "\uE0B6",
  right_rounded: "\uE0B4",
  branch: "~",
  model: "M",
  git_clean: "=",
  git_dirty: "*",
  git_conflicts: "!",
  git_ahead: "^",
  git_behind: "v",
  git_worktree: "W",
  git_tag: "T",
  git_sha: "#",
  git_upstream: ">>",
  git_stash: "S",
  git_time: "@",
  session_cost: "S",
  block_cost: "B",
  today_cost: "D",
  context_time: "C",
  metrics_response: "R",
  metrics_last_response: "L",
  metrics_duration: "T",
  metrics_messages: "#",
  metrics_lines_added: "+",
  metrics_lines_removed: "-",
  metrics_burn: "~/h",
  version: "V",
  omc_mode_ultrawork: "ULW",
  omc_mode_autopilot: "AUTO",
  omc_mode_ecomode: "ECO",
  omc_mode_inactive: "OFF",
  omc_ralph: "R",
  omc_agents: "A",
  omc_skill: "SK:",
} as const;

